const products =[
    {
        id: 0,
        name: "Table",
        price: 2500,
        oldPrice:"3500 EGP",
        dicreption:"Stylish cafe chair",
        imgSrc:"images/image 1.jpg",
        conditionClass: "sale",
        condition:"-30%",
        instock: 5,
    },
    {
        id: 1,
        name: "Chair",
        price: 2500,
        oldPrice:"",
        dicreption:"Stylish cafe chair",
        imgSrc:"images/image 2.jpg",
        conditionClass: "clear",
        condition:"",
        instock: 10,
    },
    {
        id: 2,
        name: "Sofa",
        price: 7000,
        oldPrice: "14000 EGP",
        dicreption:"Luxury big sofa",
        imgSrc:"images/image 3.jpg",
        conditionClass: "sale",
        condition:"-50%",
        instock: 20,
    },
    {
        id: 3,
        name: "Table",
        price: 500,
        oldPrice:"",
        dicreption:"Stylish cafe chair",
        imgSrc:"images/image 4.jpg",
        conditionClass: "new",
        condition:"New",
        instock: 100,
    },
    {
        id: 4,
        name: "Lampshades",
        price: 1500,
        oldPrice:"",
        dicreption:"Night lamp",
        imgSrc:"images/image 9.jpg",
        conditionClass: "clear",
        condition:"",
        instock: 15,
    },
    {
        id: 5,
        name: "Mug",
        price: 1500,
        oldPrice:"",
        dicreption:"Small mug",
        imgSrc:"images/image 6.jpg",
        conditionClass: "new",
        condition:"New",
        instock: 50,
    },
    {
        id: 6,
        name: "Bed Set",
        price: 6000,
        oldPrice: "12000 EGP",
        dicreption:"Cute bed set",
        imgSrc:"images/image 7.jpg",
        conditionClass: "sale",
        condition:"-50%",
        instock: 100,
    },
    {
        id: 7,
        name: "Couch",
        price: 12500,
        oldPrice:"",
        dicreption:"Stylish Couch",
        imgSrc:"images/image 8.jpg",
        conditionClass: "new",
        condition:"New",
        instock: 100,
    },
]